const CaptchaDefaults = {
  buildVersion: "retry-cancel-2026-04-30.2",
  allowedHost: "play.rustveil.io",
  captchaSelector: "img[alt='Captcha']",
  inputSelector: "input[maxlength='3'][inputmode='numeric']",
  submitSelector: "button.bg-amber-500",
  fallbackSubmitSelector: "button.bg-red-600",
  cancelSelector: "text:CANCEL",
  incorrectCodeText: "Incorrect code",
  preClickSelector: "button.btn-primary",
  enabled: true,
  autoFill: true,
  autoSubmit: false,
  autoRetryOnIncorrect: true,
  autoWatch: false,
  targetTabOnly: true,
  submitDelayMs: 1000,
  incorrectWaitMs: 1800,
  retryAfterCancelMs: 800,
  preClickTimeoutMs: 1000,
  maxTemplates: 600,
  templates: []
};
